apiVersion: v1
kind: Service
metadata:
  name: online-banking-service
spec:
  selector:
    app: online-banking
  ports:
    - protocol: TCP
      port: 80   # The service port exposed internally
      targetPort: 8080  # Container port where your Spring Boot app listens
  type: ClusterIP  # Change LoadBalancer to ClusterIP
