
name: Bank Backend Pipeline

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - cicd

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: digitalwitchdemo/main_bank_app_backend
        ref: main


       
    - name: Build container image
      run: docker build -t ${{ secrets.REGISTRY_NAME }}/main_bank_app_backend:$(echo $GITHUB_SHA | head -c7) .
    
    - name: Log in to Docker Registry with short-lived credentials
      run: docker login -u ${{ secrets.REGISTRY_NAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push image to Docker Registry
      run: docker push ${{ secrets.REGISTRY_NAME }}/main_bank_app_backend:$(echo $GITHUB_SHA | head -c7)


    - name: Clean up Docker image locally
      run: docker rmi ${{ secrets.REGISTRY_NAME }}/main_bank_app_backend:$(echo $GITHUB_SHA | head -c7)

    - name: Clean up GitHub repo on runner
      run: rm -rf ./*

      
  # update-argocd-payedge:
  #     runs-on: ubuntu-latest
  #     needs: build_and_push
  
  #     steps:
  #     - name: Checkout ArgoCD repository
  #       env:
  #         GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  #         GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  #       run: |
  #         git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/activedge-technologies/argocd.git
  #         cd argocd
  #         version=$(echo $GITHUB_SHA | head -c7)
  #         echo $version
  
  #     - name: Git Clone, edit and update the repo
  #       env:
  #           GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  #           GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  #           VERSION: $version
  #       run: |
  #         cd argocd
  #         git config user.email "smarta@activedgetechnologies.com"
  #         git config user.name "smartcloud2023"
          
  #         version=$(echo $GITHUB_SHA | head -c7)
  #         echo $version
  
  #         cat payassist/frontend.yaml
  #         echo 
  #         sed -i "s+registry.digitalocean.com/activedgetechnologies/payassist-frontend:.*+registry.digitalocean.com/activedgetechnologies/payassist-frontend:${version}+g" payassist/frontend.yaml
  #         cat payassist/frontend.yaml
          
  #         git add .
  #         git commit -m "Payassist frontend.yaml docker image update done by GitHub Actions run: $version"
  #         git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/activedge-technologies/argocd.git HEAD:main
  
      
  
      